DROP TABLE IF EXISTS airport;
DROP TABLE IF EXISTS country;
DROP TABLE IF EXISTS employee;
DROP TABLE IF EXISTS flightassignment;
DROP TABLE IF EXISTS job;
DROP TABLE IF EXISTS office;
DROP TABLE IF EXISTS officeshift;
DROP TABLE IF EXISTS payment;