CREATE TABLE payment (
	social_security_num VARCHAR(50) PRIMARY KEY,
    job VARCHAR(20),
    normal_hours INT,
    overtime_hours INT,
    taxes DEC(10,2),
    monthly_salary DEC(10,2)
);

insert into payment (social_security_num, job, normal_hours, overtime_hours, taxes, monthly_salary) values ('110-01-2872', 'pilot', 0, 0, 0, 0);
insert into payment (social_security_num, job, normal_hours, overtime_hours, taxes, monthly_salary) values ('107-61-8604', 'pilot', 0, 0, 0, 0);
insert into payment (social_security_num, job, normal_hours, overtime_hours, taxes, monthly_salary) values ('730-51-8952', 'pilot', 0, 0, 0, 0);
insert into payment (social_security_num, job, normal_hours, overtime_hours, taxes, monthly_salary) values ('145-84-0374', 'pilot', 0, 0, 0, 0);
insert into payment (social_security_num, job, normal_hours, overtime_hours, taxes, monthly_salary) values ('108-33-3304', 'pilot', 0, 0, 0, 0);
insert into payment (social_security_num, job, normal_hours, overtime_hours, taxes, monthly_salary) values ('620-45-9432', 'pilot', 0, 0, 0, 0);
insert into payment (social_security_num, job, normal_hours, overtime_hours, taxes, monthly_salary) values ('830-55-4393', 'pilot', 0, 0, 0, 0);
insert into payment (social_security_num, job, normal_hours, overtime_hours, taxes, monthly_salary) values ('619-11-9230', 'pilot', 0, 0, 0, 0);
insert into payment (social_security_num, job, normal_hours, overtime_hours, taxes, monthly_salary) values ('605-24-9827', 'pilot', 0, 0, 0, 0);
insert into payment (social_security_num, job, normal_hours, overtime_hours, taxes, monthly_salary) values ('500-79-5396', 'pilot', 0, 0, 0, 0);
insert into payment (social_security_num, job, normal_hours, overtime_hours, taxes, monthly_salary) values ('640-04-0209', 'copilot', 0, 0, 0, 0);
insert into payment (social_security_num, job, normal_hours, overtime_hours, taxes, monthly_salary) values ('796-77-4286', 'copilot', 0, 0, 0, 0);
insert into payment (social_security_num, job, normal_hours, overtime_hours, taxes, monthly_salary) values ('313-24-1819', 'copilot', 0, 0, 0, 0);
insert into payment (social_security_num, job, normal_hours, overtime_hours, taxes, monthly_salary) values ('791-38-6298', 'copilot', 0, 0, 0, 0);
insert into payment (social_security_num, job, normal_hours, overtime_hours, taxes, monthly_salary) values ('216-31-8755', 'copilot', 0, 0, 0, 0);
insert into payment (social_security_num, job, normal_hours, overtime_hours, taxes, monthly_salary) values ('874-40-1427', 'copilot', 0, 0, 0, 0);
insert into payment (social_security_num, job, normal_hours, overtime_hours, taxes, monthly_salary) values ('603-14-9498', 'copilot', 0, 0, 0, 0);
insert into payment (social_security_num, job, normal_hours, overtime_hours, taxes, monthly_salary) values ('386-94-2181', 'copilot', 0, 0, 0, 0);
insert into payment (social_security_num, job, normal_hours, overtime_hours, taxes, monthly_salary) values ('545-56-1535', 'copilot', 0, 0, 0, 0);
insert into payment (social_security_num, job, normal_hours, overtime_hours, taxes, monthly_salary) values ('280-33-7851', 'copilot', 0, 0, 0, 0);
insert into payment (social_security_num, job, normal_hours, overtime_hours, taxes, monthly_salary) values ('651-16-7448', 'flight attendant', 0, 0, 0, 0);
insert into payment (social_security_num, job, normal_hours, overtime_hours, taxes, monthly_salary) values ('797-34-8039', 'flight attendant', 0, 0, 0, 0);
insert into payment (social_security_num, job, normal_hours, overtime_hours, taxes, monthly_salary) values ('482-95-7866', 'flight attendant', 0, 0, 0, 0);
insert into payment (social_security_num, job, normal_hours, overtime_hours, taxes, monthly_salary) values ('380-44-9639', 'flight attendant', 0, 0, 0, 0);
insert into payment (social_security_num, job, normal_hours, overtime_hours, taxes, monthly_salary) values ('302-96-8312', 'flight attendant', 0, 0, 0, 0);
insert into payment (social_security_num, job, normal_hours, overtime_hours, taxes, monthly_salary) values ('438-83-7156', 'flight attendant', 0, 0, 0, 0);
insert into payment (social_security_num, job, normal_hours, overtime_hours, taxes, monthly_salary) values ('185-47-7772', 'flight attendant', 0, 0, 0, 0);
insert into payment (social_security_num, job, normal_hours, overtime_hours, taxes, monthly_salary) values ('505-93-2986', 'flight attendant', 0, 0, 0, 0);
insert into payment (social_security_num, job, normal_hours, overtime_hours, taxes, monthly_salary) values ('649-79-0256', 'flight attendant', 0, 0, 0, 0);
insert into payment (social_security_num, job, normal_hours, overtime_hours, taxes, monthly_salary) values ('377-44-5943', 'flight attendant', 0, 0, 0, 0);
insert into payment (social_security_num, job, normal_hours, overtime_hours, taxes, monthly_salary) values ('871-48-7269', 'flight attendant', 0, 0, 0, 0);
insert into payment (social_security_num, job, normal_hours, overtime_hours, taxes, monthly_salary) values ('715-68-4770', 'flight attendant', 0, 0, 0, 0);
insert into payment (social_security_num, job, normal_hours, overtime_hours, taxes, monthly_salary) values ('699-82-2750', 'flight attendant', 0, 0, 0, 0);
insert into payment (social_security_num, job, normal_hours, overtime_hours, taxes, monthly_salary) values ('809-07-6638', 'flight attendant', 0, 0, 0, 0);
insert into payment (social_security_num, job, normal_hours, overtime_hours, taxes, monthly_salary) values ('876-04-4208', 'flight attendant', 0, 0, 0, 0);
insert into payment (social_security_num, job, normal_hours, overtime_hours, taxes, monthly_salary) values ('744-70-9032', 'flight attendant', 0, 0, 0, 0);
insert into payment (social_security_num, job, normal_hours, overtime_hours, taxes, monthly_salary) values ('639-65-8935', 'flight attendant', 0, 0, 0, 0);
insert into payment (social_security_num, job, normal_hours, overtime_hours, taxes, monthly_salary) values ('297-87-6987', 'flight attendant', 0, 0, 0, 0);
insert into payment (social_security_num, job, normal_hours, overtime_hours, taxes, monthly_salary) values ('538-77-3150', 'flight attendant', 0, 0, 0, 0);
insert into payment (social_security_num, job, normal_hours, overtime_hours, taxes, monthly_salary) values ('358-07-0438', 'flight attendant', 0, 0, 0, 0);
insert into payment (social_security_num, job, normal_hours, overtime_hours, taxes, monthly_salary) values ('400-22-3899', 'flight attendant', 0, 0, 0, 0);
insert into payment (social_security_num, job, normal_hours, overtime_hours, taxes, monthly_salary) values ('285-83-4457', 'flight attendant', 0, 0, 0, 0);
insert into payment (social_security_num, job, normal_hours, overtime_hours, taxes, monthly_salary) values ('776-46-0405', 'flight attendant', 0, 0, 0, 0);
insert into payment (social_security_num, job, normal_hours, overtime_hours, taxes, monthly_salary) values ('270-40-3215', 'flight attendant', 0, 0, 0, 0);
insert into payment (social_security_num, job, normal_hours, overtime_hours, taxes, monthly_salary) values ('413-97-9382', 'flight attendant', 0, 0, 0, 0);
insert into payment (social_security_num, job, normal_hours, overtime_hours, taxes, monthly_salary) values ('691-97-4521', 'flight attendant', 0, 0, 0, 0);
insert into payment (social_security_num, job, normal_hours, overtime_hours, taxes, monthly_salary) values ('687-95-5086', 'flight attendant', 0, 0, 0, 0);
insert into payment (social_security_num, job, normal_hours, overtime_hours, taxes, monthly_salary) values ('707-94-2947', 'flight attendant', 0, 0, 0, 0);
insert into payment (social_security_num, job, normal_hours, overtime_hours, taxes, monthly_salary) values ('629-54-9891', 'flight attendant', 0, 0, 0, 0);
insert into payment (social_security_num, job, normal_hours, overtime_hours, taxes, monthly_salary) values ('853-49-6077', 'flight attendant', 0, 0, 0, 0);
insert into payment (social_security_num, job, normal_hours, overtime_hours, taxes, monthly_salary) values ('863-43-5607', 'flight attendant', 0, 0, 0, 0);
insert into payment (social_security_num, job, normal_hours, overtime_hours, taxes, monthly_salary) values ('620-05-0442', 'flight attendant', 0, 0, 0, 0);
insert into payment (social_security_num, job, normal_hours, overtime_hours, taxes, monthly_salary) values ('347-67-1273', 'flight attendant', 0, 0, 0, 0);
insert into payment (social_security_num, job, normal_hours, overtime_hours, taxes, monthly_salary) values ('645-26-2938', 'flight attendant', 0, 0, 0, 0);
insert into payment (social_security_num, job, normal_hours, overtime_hours, taxes, monthly_salary) values ('222-16-3379', 'flight attendant', 0, 0, 0, 0);
insert into payment (social_security_num, job, normal_hours, overtime_hours, taxes, monthly_salary) values ('763-40-1461', 'flight attendant', 0, 0, 0, 0);
insert into payment (social_security_num, job, normal_hours, overtime_hours, taxes, monthly_salary) values ('548-68-1810', 'flight attendant', 0, 0, 0, 0);
insert into payment (social_security_num, job, normal_hours, overtime_hours, taxes, monthly_salary) values ('251-49-2858', 'flight attendant', 0, 0, 0, 0);
insert into payment (social_security_num, job, normal_hours, overtime_hours, taxes, monthly_salary) values ('494-59-0750', 'flight attendant', 0, 0, 0, 0);
insert into payment (social_security_num, job, normal_hours, overtime_hours, taxes, monthly_salary) values ('327-93-1213', 'flight attendant', 0, 0, 0, 0);
insert into payment (social_security_num, job, normal_hours, overtime_hours, taxes, monthly_salary) values ('572-73-2509', 'ground crew', 0, 0, 0, 0);
insert into payment (social_security_num, job, normal_hours, overtime_hours, taxes, monthly_salary) values ('624-26-9878', 'ground crew', 0, 0, 0, 0);
insert into payment (social_security_num, job, normal_hours, overtime_hours, taxes, monthly_salary) values ('344-44-6533', 'ground crew', 0, 0, 0, 0);
insert into payment (social_security_num, job, normal_hours, overtime_hours, taxes, monthly_salary) values ('875-67-3477', 'ground crew', 0, 0, 0, 0);
insert into payment (social_security_num, job, normal_hours, overtime_hours, taxes, monthly_salary) values ('689-20-0248', 'ground crew', 0, 0, 0, 0);
insert into payment (social_security_num, job, normal_hours, overtime_hours, taxes, monthly_salary) values ('158-61-5318', 'ground crew', 0, 0, 0, 0);
insert into payment (social_security_num, job, normal_hours, overtime_hours, taxes, monthly_salary) values ('549-31-5258', 'ground crew', 0, 0, 0, 0);
insert into payment (social_security_num, job, normal_hours, overtime_hours, taxes, monthly_salary) values ('253-64-5676', 'ground crew', 0, 0, 0, 0);
insert into payment (social_security_num, job, normal_hours, overtime_hours, taxes, monthly_salary) values ('847-39-5263', 'ground crew', 0, 0, 0, 0);
insert into payment (social_security_num, job, normal_hours, overtime_hours, taxes, monthly_salary) values ('356-80-8376', 'ground crew', 0, 0, 0, 0);
insert into payment (social_security_num, job, normal_hours, overtime_hours, taxes, monthly_salary) values ('152-64-7694', 'ground crew', 0, 0, 0, 0);
insert into payment (social_security_num, job, normal_hours, overtime_hours, taxes, monthly_salary) values ('705-81-7678', 'ground crew', 0, 0, 0, 0);
insert into payment (social_security_num, job, normal_hours, overtime_hours, taxes, monthly_salary) values ('417-72-7092', 'ground crew', 0, 0, 0, 0);
insert into payment (social_security_num, job, normal_hours, overtime_hours, taxes, monthly_salary) values ('775-34-2397', 'ground crew', 0, 0, 0, 0);
insert into payment (social_security_num, job, normal_hours, overtime_hours, taxes, monthly_salary) values ('830-67-1251', 'ground crew', 0, 0, 0, 0);
insert into payment (social_security_num, job, normal_hours, overtime_hours, taxes, monthly_salary) values ('412-05-0498', 'ground crew', 0, 0, 0, 0);
insert into payment (social_security_num, job, normal_hours, overtime_hours, taxes, monthly_salary) values ('770-85-5272', 'ground crew', 0, 0, 0, 0);
insert into payment (social_security_num, job, normal_hours, overtime_hours, taxes, monthly_salary) values ('825-31-2392', 'ground crew', 0, 0, 0, 0);
insert into payment (social_security_num, job, normal_hours, overtime_hours, taxes, monthly_salary) values ('286-78-3788', 'ground crew', 0, 0, 0, 0);
insert into payment (social_security_num, job, normal_hours, overtime_hours, taxes, monthly_salary) values ('813-86-6011', 'ground crew', 0, 0, 0, 0);
insert into payment (social_security_num, job, normal_hours, overtime_hours, taxes, monthly_salary) values ('618-74-2864', 'office worker', 0, 0, 0, 0);
insert into payment (social_security_num, job, normal_hours, overtime_hours, taxes, monthly_salary) values ('883-05-1109', 'office worker', 0, 0, 0, 0);
insert into payment (social_security_num, job, normal_hours, overtime_hours, taxes, monthly_salary) values ('732-70-4655', 'office worker', 0, 0, 0, 0);
insert into payment (social_security_num, job, normal_hours, overtime_hours, taxes, monthly_salary) values ('611-25-7292', 'office worker', 0, 0, 0, 0);
insert into payment (social_security_num, job, normal_hours, overtime_hours, taxes, monthly_salary) values ('248-07-6582', 'office worker', 0, 0, 0, 0);
insert into payment (social_security_num, job, normal_hours, overtime_hours, taxes, monthly_salary) values ('422-04-9876', 'office worker', 0, 0, 0, 0);
insert into payment (social_security_num, job, normal_hours, overtime_hours, taxes, monthly_salary) values ('562-83-3028', 'office worker', 0, 0, 0, 0);
insert into payment (social_security_num, job, normal_hours, overtime_hours, taxes, monthly_salary) values ('626-55-7190', 'office worker', 0, 0, 0, 0);
insert into payment (social_security_num, job, normal_hours, overtime_hours, taxes, monthly_salary) values ('449-46-1360', 'office worker', 0, 0, 0, 0);
insert into payment (social_security_num, job, normal_hours, overtime_hours, taxes, monthly_salary) values ('306-57-0871', 'office worker', 0, 0, 0, 0);
insert into payment (social_security_num, job, normal_hours, overtime_hours, taxes, monthly_salary) values ('686-02-3446', 'office worker', 0, 0, 0, 0);
insert into payment (social_security_num, job, normal_hours, overtime_hours, taxes, monthly_salary) values ('271-55-4883', 'office worker', 0, 0, 0, 0);
insert into payment (social_security_num, job, normal_hours, overtime_hours, taxes, monthly_salary) values ('212-22-5576', 'office worker', 0, 0, 0, 0);
insert into payment (social_security_num, job, normal_hours, overtime_hours, taxes, monthly_salary) values ('261-95-1425', 'office worker', 0, 0, 0, 0);
insert into payment (social_security_num, job, normal_hours, overtime_hours, taxes, monthly_salary) values ('683-09-1046', 'office worker', 0, 0, 0, 0);
insert into payment (social_security_num, job, normal_hours, overtime_hours, taxes, monthly_salary) values ('884-53-3488', 'office worker', 0, 0, 0, 0);
insert into payment (social_security_num, job, normal_hours, overtime_hours, taxes, monthly_salary) values ('382-89-0409', 'office worker', 0, 0, 0, 0);
insert into payment (social_security_num, job, normal_hours, overtime_hours, taxes, monthly_salary) values ('360-18-7737', 'office worker', 0, 0, 0, 0);
insert into payment (social_security_num, job, normal_hours, overtime_hours, taxes, monthly_salary) values ('687-23-3706', 'office worker', 0, 0, 0, 0);
insert into payment (social_security_num, job, normal_hours, overtime_hours, taxes, monthly_salary) values ('217-29-5552', 'office worker', 0, 0, 0, 0);